[build]
  publish = "."

[[redirects]]
  from = "/"
  to = "/beginner/index.html"
  status = 200

[[headers]]
  for = "/shared/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/*.html"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
